name: CI

on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.3.2
      - name: Run detekt analysis
        run: ./gradlew detekt
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3.24.10
        if: ${{ ! cancelled() }}
        with:
          sarif_file: ./build/reports/detekt/detekt.sarif
          category: detekt

  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.3.2
      - name: Compile
        run: ./gradlew classes testClasses

  test:
    name: Test
    needs: [ compile ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.3.2
      - name: Test
        run: ./gradlew test
        id: test
      - name: Upload test report
        uses: actions/upload-artifact@v4.3.1
        if: ${{ failure() && steps.test.outcome == 'failure' }}
        with:
          name: test-report
          path: ./build/reports/tests/test/

  run:
    name: Run
    needs: [ compile ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.3.2
      - name: Run
        run: ./gradlew run --args='--help'
