name: CI

on:
  push:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Compile
        run: ./gradlew classes testClasses

  test:
    name: Test
    needs: [ compile ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Test
        run: ./gradlew test
  run:
    name: Run
    needs: [ compile ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run
        run: ./gradlew run --args='--help'
