name: CI

on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.2.0
      - name: Run detekt analysis
        run: ./gradlew detekt
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3.24.10
        if: ${{ !cancelled() }}
        with:
          sarif_file: ./build/reports/detekt/detekt.sarif
          category: detekt

  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.2.0
      - name: Compile
        run: ./gradlew classes testClasses

  test:
    name: Test
    needs: [ compile ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.2.0
      - name: Test
        run: ./gradlew test
  run:
    name: Run
    needs: [ compile ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.2.0
      - name: Run
        run: ./gradlew run --args='--help'
